slug: helm-dev
id: 89ot1lnbyxpk
title: DEV - Helm chart
teaser: Learn how to install helm charts with Instruqt
description: |-
  Learn how to build tracks with a pre-installed helm chart in this template.


  **This track will provide you with:**
    - A virtual machine with a kubernetes cluster
    - Helm already installed on the machine
    - NGINX ingress controller pre-installed on the kubernetes cluster
icon: https://raw.githubusercontent.com/instruqt/instruqt-track-assets/master/track-icons/helm.png
tags:
- dev
- dev
owner: templates
developers:
- victor@instruqt.com
- gerson@instruqt.com
private: false
published: true
maintenance: true
checksum: "17737230571645907878"
