name: CD
on:
  pull_request:
    branches:
      - main
env:
  ORGANIZATION_SLUG: templates
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
jobs:
  deploy-changes:
    name: Deploy changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Scoping tracks
        run: |
          #!/bin/bash

          # create slugs array
          slugs=()
          # Read output into an array
          shopt -s nullglob
          dirs=(*/)
          shopt -u nullglob

          for track in ${dirs[@]}; do
              # Filter all dot directories, eg. .github
              if [[ $track =~ ^\. ]]; then
                  echo "Skipping $track, not a track."
              else
                  # Strips everything including and after first '/'
                  slug=(${track//// })
                  # Adds slug to list of slugs
                  slugs+=($slug)
              fi
          done
          echo "TRACK_SLUGS=${slugs[@]}" >> $GITHUB_ENV
      - name: Pushing updated and/or new tracks
        run: |
          #!/bin/bash

          read -r -a slugs <<< "${{ env.TRACK_SLUGS }}"

          # Push every track
          for slug in ${slugs[@]}; do
              cd $slug
              docker run -e INSTRUQT_TOKEN=${{ env.INSTRUQT_TOKEN }} --workdir="/track" --mount type=bind,source="$(pwd)",target=/track instruqt/cli track push
              cd ..
          done
